ashby:
  - company: Voyant Photonics
    token: voyant-photonics
  - company: Critical Loop
    token: criticalloop

lever:
  - company: Fluxergy
    token: fluxergy-2

greenhouse:
  - company: Skild AI
    token: skildai-careers
